<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Promise最基础的版本--支持异步</title>
</head>

<body>
  <script>
    // 判断变量否为function
    const isFunction = variable => typeof variable === 'function'
    // 定义Promise的三种状态常量
    const PENDING = 'PENDING'
    const FULFILLED = 'FULFILLED'
    const REJECTED = 'REJECTED'
    class MyPromise {
      constructor(handle) {
        if (!isFunction(handle)) {
          throw new Error('MyPromise must accept a function as a parameter')
        }
        // 添加状态
        this._status = PENDING
        // 添加状态
        this._value = undefined
        // 添加成功回调函数队列
        this._fulfilledQueues = []
        // 添加失败回调函数队列
        this._rejectedQueues = []
        // 执行handle (resolve,reject)=>{},参数：_resolve,_reject
        try {
          handle(this._resolve.bind(this), this._reject.bind(this))
        } catch (err) {
          this._reject(err)
        }
      }
      // 添加resovle时执行的函数 ----------改变status的状态和value的值
      _resolve(val) {
        if (this._status !== PENDING) return
        // 依次执行失败队列中的函数，并清空队列
        const run = () => {
          this._status = FULFILLED
          this._value = val
          let cb;
          while (cb = this._fulfilledQueues.shift()) {
            cb(val)
          }
        }
        // 为了支持同步的Promise，这里采用异步调用
        setTimeout(run, 0)
      }
      // 添加reject时执行的函数
      _reject(err) {
        if (this._status !== PENDING) return
        const run = () => {
          this._status = REJECTED
          this._value = err
          let cb;
          while (cb = this._rejectedQueues.shift()) {
            cb(err)
          }
        }
        setTimeout(run, 0)
      }
      // 添加then方法
      then(onFulfilled, onRejected) {
        const { _value, _status } = this
        // 返回一个新的Promise对象
        return new MyPromise((onFulfilledNext, onRejectedNext) => {
          // 封装一个成功时执行的函数
          let fulfilled = value => {
            try {
              let res = onFulfilled(value);
              onFulfilledNext(res)
            } catch (err) {
              onRejectedNext(err)
            }
          }

          // 封装一个失败时执行的函数
          let rejected = value => {
            try {
              let err = onRejected(value);
              onFulfilledNext(err)
            } catch (err) {
              onRejectedNext(err)
            }
          }

          switch (_status) {
            // 当状态为pending时，将then方法回调函数加入执行队列等待执行
            case PENDING:
              this._fulfilledQueues.push(fulfilled)
              this._rejectedQueues.push(rejected)
              break
            case FULFILLED:
              fulfilled(_value)
              break
            case REJECTED:
              rejected(_value)
              break
          }
        })
      }
      // 添加catch方法
      catch(onRejected) {
        return this.then(undefined, onRejected)
      }
    }
  </script>
  <script>
    let p1 = new MyPromise((resolve, reject) => {
      resolve('成功1')
    })
    let p2 = p1.then(res => { throw new Error('error') })
    p2.then(res => { console.log(res, 'success2'); }, err => { console.log(err, 'fail'); return 1111; })
  </script>
</body>

</html>
